# -*- nginx -*-

location ~ ^/n/.+\.(css|js)$ {
    gzip                on;
    gzip_comp_level     5;
    gzip_min_length     256;
    gzip_proxied        any;
    gzip_types          *;
    gzip_vary           on;

    expires             1w;
    add_header          X-Powered-By CCNRv2;
}

location ~ ^/n/.+\.(jpe?g|png)$ {
    expires             max;
    add_header          X-Powered-By CCNRv2;
}
